### PR TITLE
Set dynamic pathing

### PR DESCRIPTION
**Pull request by dadreggors**
Remove relative paths ('temp/blah.text')
Use __dirname to get script path
Set tmp path using found script path
Create all files and folders as needed

### CODE REVIEW

**Comment by ianwillie** [comment]
Hi thanks, you've done a lot of work.
I am relatively new to git & extremely new to github. I have gone through your suggestions and they look appropriate on first look.  I will take a day or two to work out how to implement these because I have gone and mucked up my git main by merging something into from a testing branch by accident. I can find no way to undo it. In the past when I have done this I think I just rebase eveything or use a local backup of the entire project. However, with your interest in the package it will muck things up for you.  
I will get back to you, thanks so much for your help.

On a slightly different note. I find the preview of the asciidoc files in pulsar relatively useless. This seems to be because all sorts of things are constrained by what I take to be security limitations in the editor package.  Scrolling does not work properly and for zoom I use the chrome style extension. Also most of the links do not work in the preview including moving around within the html file..
To be honest I find it far more acceptable to simply open the html5 file created by asciidoc in falkon by pressing Ctrl+Alt+F. Then in the browser window virtually everything works out of the box just as it would in a real including zoom. scroll. Automatic update when the source file is saved in pulsar works because falkon has creates its own local server.
I have wondered about removing the ascidoc preview in pulsar and just using the falkon browser as described above and concentrating on making that  synchronise wi the pulsar editor.

**Review by ianwillie — COMMENTED** [review]
Thanks for all this. It has made me contemplate quite a few issues and why I have choosen to do things in particular ways over the 9 months or so of developing this package encouraged by several promenant  figures in the pulsar devlopment scene.

The simple one line changes  const https = require('https');, l213 console.log(previewPaneWidth); } are fine and I will incorporate them and push them. Also the atom-browser.less file error which I have tracked down to a line in the ...view.js file which should have been deleted - for now just ignore the error.

The directory changes are a different matter altogether.   It is importance that the base directory be relative and ./ is what I found worked best. __dirname leads to an absolute directory name and will not work in the ...view file. See https://stackoverflow.com/questions/8131344/what-is-the-difference-between-dirname-and-in-node-js#18283508
It seems best to me that the links should be relative in the generated html file. Absolute links may work on a local system but are not transferrable I think.

However, I like the way you have the try/catch setup which I have recently stated trying to use more. 

The asciidoctor.css issue is very complex. From within an adoc file we can control how the css is used provided the generated html is "standalone". However if the file is "embedded" then there is no head section and the css must be controlled from the generated html  (l268  in ...view.js file hN +=   `    <link rel="stylesheet" href="${getAsciidoctorCssPath()}">\n`; ).
What I am contemplating at the moment is generating an adoc standalone file and extracting from that the css information generated from the source adoc file and then interpolating it into the  embedded adoc file. This would then allow the css to be controlled completely from the originating adoc file. Whether this would work remains to be seen. I also like to be able to edit my ascidoctor.css by hand. Also it is handy to be able to have the ...view.js file be able to alter styles or even alter the css file itself.
See https://docs.asciidoctor.org/asciidoctor/latest/html-backend/default-stylesheet/
I think this implies that the adoc css files should not be put in the css directory but are generally expected by asciidoctor.js to be in the same dir as the originating .adoc file. 

As far as changing the name of the temp dir to tmp that would cause problems to the many  projects for which I use my package. Maybe temp was not such a good name but I feel I would benefitting from  sticking to it.  In my experience tmp is used as a transient directory which vanishes on logout. The temp dir I use remains after the logout and is used as the basis of an number of things in the next login like to where the html file scrolls, zoom and so on.  I have quite a few branches where I have been trying fairly fundamental differences to explore how the synchronise the cursor position in the adoc view in pulsar and in the browser.

I wonder if you would  consider making a fork of my package and implementing the changes that you have outlined that you would prefer. We would all benefit by seeing your experience of the alterations.

I am a bit disorganised with all this because when I find something that I would like changed I just go into the package files and alter the code.  I have been learning to create branches to do this. But I am very much a beginner.

I do appreciate your interest and thinking about all this.  No doubt I will come back and edit some of this which is very much my first thinking on the matter.  I look forward to hearing your thoughts.

**Comment by dadreggors** [comment]
>  It is importance that the base directory be relative and ./ is what I found worked best. __dirname leads to an absolute directory name and will not work in the ...view file.

So this one is perplexing to me. I do not 100% understand this response (or rather possibly what you see that differs than on my system). So here is what I found when using relative paths for temp:

The relative path (`./temp` for example) ends up working out to the path of your adoc file's directory. So, if I preview an adoc file in `${HOME}/Documents` it wants  there to be a temp folder in that directory (`${HOME}/Documents/temp`) which now leaves a bunch of temporary render files in that temp folder. Now, if I preview another adoc file in ANOTHER location (say `${HOME}/git/myproject/README.adoc`) it now needs a temp folder there as well (again leaving all temp render files in that new temp folder). 

So, the issue I see with this method is that we create new temp folders all over the filesystem versus in one location (like the plugin tree `.pulsar/packages/ianasciidocpreview-active-editor-info`). To make matters worse, many times developers who are writing adoc files and need a preview are in a git repository and these temp files could (and will) then get checked into git accidentally.

It is far better to set an output dir variable to a known path that is safe and use that variable everywhere to write all files to that path. You will note that I also had to *add* code to create the required temp directory if it does not exist. This further reduces errors (the file not found errors I saw). The way your code writes files, these temp files get overwritten every time (as it should be) 


**POSSIBLE ISSUE**
Rendering 2 or more adoc files at the same time. 

That problem can also be solved by appending a random suffix to the HTML output folder for each operation. Then, since we capture that folder name in the variable THIS operation in memory will always find the correct path with a random suffix (see `/tmp` on any Linux box).  Now as you complete each preview you will cleanup files left behind.

**Comment by dadreggors** [comment]
Just wanted to add:

You are doing great and I applaud you for learning all of this. Whatever direction you take will be awesome because you are learning new stuff every day. I agree on the complexities of all this and I wish I had the time to devote more to this. I simply just don't have that time. 

I am happy to contribute and test here and there, but cannot fork and devote time to this (that could change here and there and allow more time though).  Do not take my suggestions as criticisms as they are not. You are doing way more than I can so YOU ROCK.  I am just trying to add what I can here :-)

**Comment by ianwillie** [comment]
It has dawned on me that we have a different way of working and we are ending talking at cross purposes while we agree, I think that is the case anyway.

> The relative path (./temp for example) ends up working out to the path of your adoc file's directory. So, if I preview an adoc file in ${HOME}/Documents it wants there to be a temp folder in that directory (${HOME}/Documents/temp) which now leaves a bunch of temporary render files in that temp folder. Now, if I preview another adoc file in ANOTHER location (say ${HOME}/git/myproject/README.adoc) it now needs a temp folder there as well (again leaving all temp render files in that new temp folder)

The above is exactly the way that I want things. I use asciidoc only for very large projects with say 600 web pages and many links to subdirectory levels with the final child pages with 100s of links to the likes of GoogleNew[papers]. Each subdirectory level has its own index.html with links into the next subdirectory which has its own index.html page and so on.  What happens is that the temp directory is placed at the top project level directory regardless of which subdirectory files pulsar is editing.  The various files in the temp directory  (like ```htmloutputFileRawFromAsciidoc.html,  iansasciidocpreviewhtmloutput.html, iansasciidocpreviewscrolltohere.txt,  iansasciidocpreviewtransformscale.txt &  XXXasciidocInputFromEditor_words```) get reused in the single temp dir for each adoc file previewed. That is what I experience anyway. There are no temp directories in any of the subdirectories no matter which adoc file I edit in pulsar. I aways run ```/home/ian/Downloads/pulsarlatest . --no-sandbox``` from a terminal in the top project directory. If I accidentally enter pulsar from say the lib/ directory then I will end up with a lib/temp dir there. So as long as I always enter pulsar from the top ProjectDirectory I'll get the structure listed below. I have added a few comments. (The extra extentions .html.erb in addition to adoc are because I use Middleman CMS for the static websites and it uses Ruby hence ".erb".)

```
ProjectDirectory
├── source
│   ├── Press
│   │   ├── GlasgowHerald
│   │   │   ├── GlasgowHerald1971.html.erb.adoc
│   │   │   ├── GlasgowHerald1972.html.erb.adoc
│   │   │   ├── index.html.erb.adoc  # index to GlasgowHerald
│   │   ├── Guardian
│   │   │   ├── index.html.erb.adoc
│   ├── DiverseArtists
│   │   ├── Exhibitions
│   │   │   ├── ExhibitionA.html.erb.adoc
│   │   │   ├── ExhibitionB.html.erb.adoc
│   │   ├── Shows
│   │   ├── index.html.erb.adoc
│   ├── index.html.erb.adoc     # index to Press
├── index.html.erb.adoc         # main index to all levels
├── temp                        # the only temp directory for all directies.
│   ├── htmloutputFileRawFromAsciidoc.html
│   ├── iansasciidocpreviewhtmloutput.html
│   ├── iansasciidocpreviewscrolltohere.txt
│   ├── iansasciidocpreviewtransformscale.txt
│   ├── XXXasciidocInputFromEditor_words
│   └── XXX.txt

```

Now, as you point out,  if we have lots independent adoc pages in their own directories, each will have its own temp directory, and yes there will be lots of these all over the place.
I think that we can easily accommodate both ways of working by a couple of possibilites which come to mind:
1. Have the option to delete the temp file when we finish editing the adoc file, or
2.  Choose where the  htmloutputDir  will be either  "./", or some other directory like "/home/myhome/AllMyAdocPreviewTempFiles" .  This would need a bit more thought.

I should add that the reason for communicating between the javascript file and the preview is that it is the only way that I found I could incorporate parameters (like zoom factor) into the preview html file. They are incorporated into the html strings that will eventually be written to the file iansasciidocpreviewhtmloutput.html which is the actual file which  becomes the code in pulsar that is the preview pane. Ordinary panes in pulsar are not allowed to fun javascript scripts. Neither are they able to jump to internal likes, although they seem to be able to run some external files like youtube videos.  To communicate at greater depth seems to require access to electron ipc code which is what I was trying to avoid  sticking to html5. As I have discussed before this limits the capabilities of the pulsar pane but works fine when viewed in an external browser like Falkon which has its own server.  Incidentally  iansasciidocpreviewhtmloutput.html works fine when opened in pulsar and viewed in html-preview  using Ctrl-Shift-H.

THis is all for now. But thanks so much for your interest and taking time to think about it all and comment.  No one else has done that and what I need is an outside referee - thee!

**Comment by ianwillie** [comment]
I've created a branch Test_Changing_htmloutputDir  which puts the temp directory in /home/<user>/ZZZZianasciidocpreview-active-editor-info/temp/ . This is based on a minimal change to my original main push.  All the same files as before should appear in temp/. Many thanks to @dadreggors  for the stimulation as to why this might be a useful change.
Please try this and let me know how you get on.
The htmloutputDir can be changed  to "./" to have the temp/ directory appear in the project directory. See the comments in the lib/...view.js file for how to do this.   

(There are several new .html files starting htmloutputFileRawFromAsciidoc which show different modes of asciidoctor.js  .adoc conversions. In the future these will be used to generate the linked style css files which will be incorporated into the outputhtml file.  Eventually, but not yet, this output will be controlled from within the .adoc file  as css attributes.) 

Note: this is the first time I have pushed a branch, so it might not have gone according to plan. Please let me know.

EDIT: Ignore the comment in next paragraph because only I see the conflict referred to  when logged in. Others see main & branch "Test_Changing_htmloutputDir" correctly as expected.

EDIT: The following paragraph should be strikthrough (but formatting is not allowed by github apparently.
 ~~There is a comment following that there are conflicts between this site main & @dadreggors  main.  I am confused by this because of my inexperience of github. However as far as I can see the branch "Test_Changing_htmloutputDir" is as it should be and downloading that should be OK. ~~

**Pull request closed without merging**
